const AUTHORIZATION_REQUEST = 'AUTHORIZATION_REQUEST';
const AUTHORIZATION_SUCCESS = 'AUTHORIZATION_SUCCESS';
const AUTHORIZATION_FAILURE = 'AUTHORIZATION_FAILURE';

const OMELUSIK = {
    status: "pidor",
};

export {AUTHORIZATION_REQUEST, AUTHORIZATION_SUCCESS, AUTHORIZATION_FAILURE};


c